config/routes.rb
Rails.application.routes.draw do

  root 'data#upload'

  get 'data/upload'
  post 'data/process', to: 'data#handle_upload', as: 'data_handle_upload'
  get 'data/map'
  get 'data/stats'
  get 'data/chart'
  get 'data/select'
  get 'data/select/:id', to: 'data#select_journey', as: 'data_select_journey'

  get 'login', to: 'login#index', as: 'login'
  get 'logout', to: 'login#logout', as: 'logout'
  post 'login/auth'

end

app/models/journey.rb
class Journey < ActiveRecord::Base
  require 'floow/lat_long'
  require 'floow/sql_insert_batcher'

  belongs_to :user

  def self.create_from_csv(csv, user_id)
    journey = Journey.new

    journey.user_id = user_id

    journey.save

    row_index  = 0
    distance   = 0
    prev_point = nil

    column_names       = %w(journey_id row_index distance timestamp speed altitude latitude longitude)
    sql_insert_batcher = Floow::SqlInsertBatcher.new('journey_datum', column_names)

    csv.each do |row|
      millis    = row['millis'].to_f
      speed     = row['speed'].to_f
      altitude  = row['altitude'].to_f
      latitude  = row['latitude'].to_f
      longitude = row['longitude'].to_f

      curr_point = Floow::LatLong.new(latitude, longitude)

      if prev_point != nil
        distance = prev_point.distance curr_point
      end

      sql_insert_batcher.push [
        journey.id,
        row_index,
        distance,
        millis,
        speed,
        altitude,
        latitude,
        longitude,
      ]

      prev_point = curr_point

      row_index += 1
    end

    sql_insert_batcher.flush

    return journey
  end

  def start_timestamp
    @start_timestamp = Time.at((journey_datums.minimum(:timestamp) || 0) / 1000).to_datetime
  end

  def end_timestamp
    @end_timestamp ||= Time.at((journey_datums.maximum(:timestamp) || 0) / 1000).to_datetime
  end

  def total_distance
    @total_distance ||= journey_datums.sum(:distance)
  end

  def max_speed
    @max_speed ||= journey_datums.maximum(:speed)
  end

  def average_speed
    @average_speed ||= journey_datums.average(:speed)
  end

  def max_altitude
    @max_altitude ||= journey_datums.maximum(:altitude)
  end

  def min_altitude
    @min_altitude ||= journey_datums.minimum(:altitude)
  end

  def average_altitude
    @average_altitude ||= journey_datums.average(:altitude)
  end

  def highest_point
    if @highest_point
      return @highest_point
    end

    journey_datums.each do |datum|
      if datum.altitude == max_altitude
        @highest_point = Floow::LatLong.new(datum.latitude, datum.longitude)
        break
      end
    end

    @highest_point
  end

  def first_point
    journey_datums.first.to_lat_long
  end

  def last_point
    journey_datums.last.to_lat_long
  end

  def central_point
    if @central_point
      return @central_point
    end

    latitude  = (journey_datums.maximum(:latitude) + journey_datums.minimum(:latitude)) / 2
    longitude = (journey_datums.maximum(:longitude) + journey_datums.minimum(:longitude)) / 2

    @central_point = Floow::LatLong.new(latitude, longitude)
  end

  def formatted_timespan
    start_date = start_timestamp.strftime('%d/%m/%Y')
    end_date   = end_timestamp.strftime('%d/%m/%Y')
    start_time = start_timestamp.strftime('%H:%M')
    end_time   = end_timestamp.strftime('%H:%M')

    start_date + ' ' + start_time + ' - ' + (end_date != start_date ? end_date + ' ' : '') + end_time
  end

  # Returns a path string that can be used to describe the journey to the Google Maps API
  def gmaps_path
    points = []

    # we can't include every point, because there's a limit on how long a query string can be
    max_points = 50
    step_size  = [(journey_datums.length / max_points).floor, 1].max
    journey_datums.where('row_index % ' + step_size.to_s + ' = 0').each do |journey_datum|
      points.push journey_datum.to_lat_long.to_coords
    end

    # always include the last point
    points.push last_point.to_coords

    points.join('|')
  end

  has_many :journey_datums
end

app/models/journey_datum.rb
class JourneyDatum < ActiveRecord::Base
  require 'floow/lat_long'

  def to_lat_long
    Floow::LatLong.new(latitude, longitude)
  end

  belongs_to :journey
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :journeys
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

  helper_method :current_user, :logged_in?

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  private
  def require_login
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  require 'csv'

  before_filter :require_journey

  helper_method :current_journey, :has_journey?, :journeys_available?

  def upload
    # Empty controller action
  end

  def handle_upload
    uploaded_io = params[:journey_csv]
    if uploaded_io
      csv = CSV.parse(File.read(uploaded_io.path), :headers => true)

      journey = Journey.create_from_csv(csv, current_user.id)
      session[:journey_id] = journey.id

      redirect_to data_map_path and return
    end

    flash[:danger] = 'Upload failed'
    redirect_to data_upload_path
  end

  def map
    # Empty controller action
  end

  def stats
    # Empty controller action
  end

  def chart
    render layout: 'full_width'
  end

  def select
    # Empty controller action
  end

  def select_journey
    session[:journey_id] = params[:id]
    redirect_to data_map_path
  end

  protected

  # Returns the current journey (if any).
  def current_journey
    @current_journey ||= Journey.find_by(id: session[:journey_id])
  end

  # Returns true if the user has a current journey, false otherwise.
  def has_journey?
    !current_journey.nil?
  end

  def journeys_available?
    !current_user.journeys.nil?
  end

  private
  def require_journey
    journey_actions = %w(map stats chart)
    if journey_actions.include? action_name and !has_journey?
      flash[:warning] = 'No journey'
      redirect_to data_upload_path
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  skip_before_filter :require_login

  def index
  end

  def auth
    username = params[:login][:username]
    password = params[:login][:password]

    user = User.find_by(username: username)
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to data_upload_path
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def logout
    session.delete(:user_id)
    session.delete(:journey_id)
    flash[:success] = 'You have been logged out'
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper

end

app/views/data/_menu.html.erb
<ul>
    <li class="first"><a href="/">Upload</a></li>
    <% if has_journey? %>
        <li><%= link_to 'Map', data_map_path %></li>
        <li><%= link_to 'Stats', data_stats_path %></li>
        <li><%= link_to 'Speed Chart', data_chart_path %></li>
    <% end %>
    <% if has_journey? or journeys_available? %>
        <li><%= link_to 'Select', data_select_path %></li>
    <% end %>
  <li class="last"><%= link_to 'Log out', logout_path %></li>
</ul>

app/views/data/chart.html.erb
<% content_for :head do %>
    <script type="text/javascript">
        /**
         * Generate the speed graph
         *
         * @param {object}   container the container DOM object to generate the graph into
         * @param {object[]} rows      the route data
         */
        function generateSpeedGraph(container, rows)
        {
            var speedFunc = function(row) {return row.speed;};
            var timeFunc  = function(row) {return row.time;};

            var avgSpeed = d3.sum(rows, speedFunc) / rows.length;
            var maxSpeed = d3.max(rows, speedFunc);

            var minTime = d3.min(rows, timeFunc);
            var maxTime = d3.max(rows, timeFunc);

            var avgMark = floow.graph.line.horizontalMark(maxSpeed)
                .label('Fastest Speed: ' + maxSpeed.toFixed(2) + ' kph');
            var maxMark = floow.graph.line.horizontalMark(avgSpeed)
                .label('Average Speed: ' + avgSpeed.toFixed(2) + ' kph');

            var graph = floow.graph.line()
                .height(400)
                .margins(5, 5, 55, 45)
                .data(rows)
                .xDomain(minTime, maxTime)
                .yDomain(0, 1.10 * maxSpeed)
                .xFunc(timeFunc)
                .yFunc(speedFunc)
                .xTickFormatter(function(time) {return time.toLocaleTimeString();})
                .yTickFormatter(function(speed) {return speed + ' kph';})
                .addHorizontalMark(maxMark)
                .addHorizontalMark(avgMark);

            container.call(graph);
        }

        $(document).ready(function() {
            var rows = [
                <% current_journey.journey_datums.each do |datum| %>
                    {time: new Date(<%= datum.timestamp %>), speed: <%= datum.speed %>},
                <% end %>
            ];
            generateSpeedGraph(d3.select("#speedGraph"), rows);
        });

    </script>
<% end %>

<h1>Speed Chart</h1>
<div id="speedGraph" class="block"></div>

app/views/data/map.html.erb
<% content_for :head do %>
    <script type="text/javascript">
        var API_KEY = 'AIzaSyC8oiTZM3rI7Ugl3RKKL4Uk_cxG1M_YICo';

        function loadJourneyMap(container) {
            var img = $('<img>');
            var width = 600;
            var height = 400;

            var baseUrl = 'https://maps.googleapis.com/maps/api/staticmap';
            <% journey = @current_journey %>
            var queryParams = [
                ['center', '<%= journey.central_point.to_coords %>'],
                ['path', 'color:red|weight:3|<%= journey.gmaps_path %>'],
                ['size', width + 'x' + height],
                ['markers', 'color:red|label:S|<%= journey.first_point.to_coords %>'],
                ['markers', 'color:red|label:F|<%= journey.last_point.to_coords %>'],
                ['key', API_KEY]
            ];
            var src = floow.url.build(baseUrl, queryParams);

            img.attr('width', width);
            img.attr('height', height);
            img.attr('src', src);

            container.append(img);
        }

        $(document).ready(function() {
           loadJourneyMap($('#journeyMap'));
        });
    </script>
<% end %>


<h1>Journey Map</h1>
<p id="journeyMap"></p>

app/views/data/select.html.erb
<h1>Journey List</h1>
<% current_user.journeys.each do |journey| %>
    <ul class="large_list">
        <li>
          <%= link_to journey.formatted_timespan + ' Journey', data_select_journey_path(journey) %>
        </li>
    </ul>
<% end %>

app/views/data/stats.html.erb
<h1>Journey Stats</h1>
<table class="keyValue">
    <tbody>
        <tr>
            <th>Distance Travelled:</th>
            <td><%= (current_journey.total_distance / 1000).round(2) %> km</td>
        </tr>
        <tr>
            <th>Fastest Speed:</th>
            <td><%= current_journey.max_speed.round(2) %> kph</td>
        </tr>
        <tr>
            <th>Average Speed:</th>
            <td><%= current_journey.average_speed.round(2) %> kph</td>
        </tr>
        <tr>
          <th>Highest Point:</th>
          <td><%= current_journey.highest_point.to_html %></td>
        </tr>
        <tr>
          <th>Average Altitude:</th>
          <td><%= current_journey.average_altitude.round(2) %> m</td>
        </tr>
        <tr>
          <th>Central Point:</th>
          <td><%= current_journey.central_point.to_html %></td>
        </tr>
    </tbody>
</table>

app/views/data/upload.html.erb
<h1>Upload CSV File</h1>

<div class="info_block">
  <p>Your journey file should be a csv with the following column headings:</p>
  <ul class="large_list">
    <li>millis</li>
    <li>speed</li>
    <li>altitude</li>
    <li>latitude</li>
    <li>longitude</li>
  </ul>
</div>

<%= form_tag(data_handle_upload_path, multipart: true) do %>
    <%= file_field_tag 'journey_csv', class: 'form-control' %>

    <%= submit_tag 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="copy">

        <p class="left">
            <span class="eu_charter">
                The Floow is a signature of the
                <a href="http://www.erscharter.eu" target="_blank">European Road Safety Charter</a>
            </span>
            <span class="rospa_member">
                The Floow is a member of the
                <a href="http://www.rospa.com/" target="_blank">Royal Society for Prevention of Accidents</a>
            </span>

        </p>
        <p class="right">
            &copy; copyright 2012-2014 The Floow Limited - All rights reserved<br> Designed in Yorkshire
        </p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="centered_area">
        <em id="logo">
            <%= link_to 'The Floow', '/' %>
        </em>
        <nav id="top_level_menu">
            <ul data-breakpoint="600" class="flexnav one-page">
                <nav class="menu clearfix" id="menu">
                  <%= render 'menu' %>
                </nav>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telemetrics App</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Noticia+Text:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="/assets/favicon.png">
    <%= yield :head %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <div id="outer_wrapper">
      <%= render 'layouts/header' %>
      <div class="container">
        <div class="centered_area">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/full_width.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telemetrics App</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Noticia+Text:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="/assets/favicon.png">
    <%= yield :head %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <div id="outer_wrapper">
      <%= render 'layouts/header' %>
      <div class="container">
        <div class="centered_area">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <div class="expanding_area">
          <%= yield %>
        </div>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/login/_menu.html.erb
<ul>
    <li class="first last selected">
      <%= link_to 'Login', login_path %>
    </li>
</ul>

app/views/login/index.html.erb
<% provide(:title, 'Log in') %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:login, url: login_auth_path) do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit 'Log in', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>